### ISSUE TITLE
Replace with retrieval from "input.if", which provides safer parsing

### ISSUE THREAD

**Issue by ldesio** [ldesio/staR#9]
https://github.com/ldesio/staR/blob/d5eb3a8cf4dcc481325095ba20b9bedbc2aaffc0/app/static/commands/replace.js#L28

**Comment by ldesio** [comment]
Also for

https://github.com/ldesio/staR/blob/d5eb3a8cf4dcc481325095ba20b9bedbc2aaffc0/app/static/commands/replace.js#L28

**Comment by giucarny** [comment]
https://github.com/ldesio/staR/blob/1ab6ccdc81e98bbeda353ae8b09af429b9878e14/app/static/commands/replace.js#L28
